config/routes.rb
Rails.application.routes.draw do
  resources :documents
  root to: "documents#index"
end

app/models/document.rb
class Document < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader

  scope :by_newest, -> { order("created_at DESC") }

  default_scope { by_newest }

  validates_with AttachmentValidator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from Errno::ENOENT, with: :record_not_found
  protect_from_forgery with: :exception
  responders :flash

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  private

  def record_not_found
    render file: "public/422", status: 422
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  respond_to :html

  expose(:document, attributes: :document_params)
  expose(:documents) { Document.page(params[:page]) }

  expose(:document_presenter) { DocumentPresenter.wrap(document) }
  expose(:documents_presenter) { DocumentPresenter.wrap(documents) }

  def create
    if document.save
      flash[:notice] = "Document was successfully created."
      redirect_to documents_path
    else
      respond_with(document)
    end
  end

  def update
    flash[:notice] = "Document was successfully updated." if document.save
    respond_with(document)
  end

  def destroy
    document.destroy
    respond_with(document)
  end

  private

  def document_params
    params.require(:document).permit(:name, :attachment, :remote_attachment_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def word_formats
    %w(.doc .docx)
  end
end

app/views/application/_footer.html.slim
.row
  footer
    .columns
      p &copy; FlatStack #{Date.today.year}

app/views/application/_messages.html.slim
- flash.each do |type, content|
  div(data-alert class="alert-box #{type}")
    = content
    a.close &times;

app/views/application/_navigation.html.slim
nav.top-bar( data-topbar )

  ul.title-area
    li.name
      h1 = link_to t('titles.application'), root_path
    li.toggle-topbar
      a(href='#')
        i.fi-list

  section.top-bar-section
    = render 'navigation_main'

app/views/application/_navigation_main.html.slim
ul.left
  = active_link_to 'Home', root_path, active: :exclusive, wrap_tag: :li

app/views/documents/_document.html.slim
.row
  - if word_formats.include? document.extension
    = render "word", document: document
  - else
    = render "excel", document: document
br
br
hr

app/views/documents/_excel.html.slim
- if document.extension == ".xls"
  .xls
    = sanitize document.attachment_ms_excel
- else
  .xlsx
    - document.attachment_ms_excel.worksheets.each do |worksheet|
      h3 = worksheet.sheet_name
      table.excel-table
        tbody
          - worksheet.extract_data.try(:each) do |row|
            tr
              - row.try(:each) do |cell|
                td.excel-cell = cell || ""
      br
      br
      br

app/views/documents/_form.html.slim
.scaffold-form
  = simple_form_for(document) do |f|
    .form-inputs
      = f.file_field :attachment
      | Or attach url
      = f.text_field :remote_attachment_url
    .form-actions
      = f.button :submit
      '  or
      = link_to 'Back', :back

app/views/documents/_word.html.slim
.word
  = document.content_ms_word

app/views/documents/edit.html.slim
= render 'form'

app/views/documents/index.html.slim
.row
  table.table.table-striped
    thead
      caption
        span.table-name= "My Documents"
        span.new-doc= link_to new_document_path, class: "button tiny"
          |  New Document
      tr
        th Name
        th Path
        th Actions
    - documents_presenter.each do |document|
      tr
        td= document.name
        td= document.path

        td.actions
          = link_to " Preview", document_path(document.id), class: "fi-eye"
          br
          = link_to(document, confirm: "Are you sure?", method: :delete, class: "btn btn-danger") do
            i.fi-trash
            |  Delete

app/views/documents/new.html.slim
h3
  | Create Document
= render 'form'

app/views/documents/show.html.slim
= link_to 'Back', root_path
hr
= render "document", document: document_presenter

app/views/layouts/application.html.slim
doctype html

html class='no-js' lang='en'

  head
    meta charset='utf-8'
    meta name='viewport' content='width=device-width, initial-scale=1.0'

    title= title

    = csrf_meta_tags

    /! Le styles
    = stylesheet_link_tag :application

    /! Le modernizr
    = javascript_include_tag 'vendor/modernizr'

  body
    #root
      = render 'navigation'
      = render 'messages'

      = yield

    = render 'footer'

    = javascript_include_tag :application